### ISSUE TITLE
Should we add a dependency on ChainRulesCore?

### ISSUE THREAD

**Issue by mzgubic** [invenia/NamedDims.jl#177]
I ran into 
```julia
gradient((values, names) -> sum(NamedDimsArray(values, names)), rand(2, 3), (:a, :b))

ERROR: Need an adjoint for constructor NamedDimsArray{(:node, :target), Float32, 2, Matrix{Float32}}. Gradient is of type NamedDimsArray{(:node, :target), Float32, 2, Matrix{Float32}}...
```
error when using Zygote to AD through some code using NamedDimsArrays. It can be solved by pirating
```julia
function ChainRulesCore.rrule(::Type{NamedDimsArray}, values, names)
    NamedDimsArray_pullback(ȳ::AbstractArray) = (NoTangent(), ȳ, NoTangent())
    NamedDimsArray_pullback(ȳ::Tangent) = (NoTangent(), ȳ.data, NoTangent())
    NamedDimsArray_pullback(ȳ::AbstractThunk) = NamedDimsArray_pullback(unthunk(ȳ))
    return NamedDimsArray(values, names), NamedDimsArray_pullback
end
```

The question is, do we want to add a dependency on ChainRulesCore to the package and fix this here? I think we do

**Comment by oxinabox** [comment]
Yes, we do.
I mean ideally, a NamedDimsArray would just work since it is a very standard dense wrapper array.
But since it dopesn't then it doesn't.

This is BTW one of the cass where moving outside of the local space fixes type inference.
https://github.com/JuliaLang/julia/issues/40990
See [docs](https://juliadiff.org/ChainRulesCore.jl/dev/writing_good_rules.html#Be-careful-about-pullback-closures-calling-other-methods-of-themselves)

```julia
NamedDimsArray_pullback(ȳ::AbstractArray) = (NoTangent(), ȳ, NoTangent())
NamedDimsArray_pullback(ȳ::Tangent) = (NoTangent(), ȳ.data, NoTangent())
NamedDimsArray_pullback(ȳ::AbstractThunk) = NamedDimsArray_pullback(unthunk(ȳ))

function ChainRulesCore.rrule(::Type{NamedDimsArray}, values, names)
    return NamedDimsArray(values, names), NamedDimsArray_pullback
end
```
