### ISSUE TITLE
AbstractNamedDim type?

### ISSUE THREAD

**Issue by Tokazama** [invenia/NamedDims.jl#32]
Related to #29 

Would it be in line with the goals of this package to provide an abstract type and opt in methods that facilitates NamedDims functionality? Otherwise other packages will need to use something like `Lazy.@forward` to make their own matrix types. If this sounds like a reasonable path forward I'd be willing to take a crack at it now that I have some time.

**Comment by oxinabox** [comment]
In general, extending this is done via type-parameter.

You want a `NamedFooArray` then you wrap a `FooArray` in a `NamedDimsArray`
```
const NamedDimsFooArray{L, T, N} = NamedDimsArray{L, T, N, FooArray{T, N}}
```

Or even with labels I hope:
```
const ModelArray = NamedDimsArray{(:variates, :covariates}, Float64, 2, Array{Float64, 2}}
```

If we need things that can't do, then I hope that we can do this via traits, rather than inheritance.
Because we want to be able to mix the `IndexedArray` type with the `NamedDimsArray` type.

**Comment by Tokazama** [comment]
Got it. Thanks for the clarification.
