### ISSUE TITLE
A  method to that converts a NamedDimsArray to its parent, and makes no change to anything else

### ISSUE THREAD

**Issue by oxinabox** [invenia/NamedDims.jl#39]

**Comment by nickrobinson251** [comment]
Checking I understand:
- `parent(nda)` returns a view, this new function should be `copy(parant(nda))`
- `collect(nda)` does copy but isn't what we want here, because it will return an `Array` whereas the `parent` might be some other `AbstractArray` type

Do we just need to pick a name `f` and then define `f(nda::NamedDimsArray) = copy(parent(nda))`?

**Comment by oxinabox** [comment]
No, this function should be literally:

```
unname(x::AbstractArray) = x
unname(nda::NamedDimsArray = parent(x)
```

But idk what to call it.
Tracker.jl calls this `data`.

**Comment by nickrobinson251** [comment]
AxisArrays also basically calls this `data` i.e. you can do `A.data` to get this... but I dislike calling anything `data`; it basically means you gave up on finding a name.

 `unname` seems better -- why not that?

**Comment by nickrobinson251** [comment]
but also isn't this just `parent`?

**Comment by oxinabox** [comment]
> AxisArrays also basically calls this data i.e. you can do A.data to get this... but I dislike calling anything data; it basically means you gave up on finding a name

No, not the same
because `[1 2 3].data`
will throw an error.

More generally though, it is an emergent convention for wrapper arrays that the inner array fields is called `data`.
i.e. that `parent(x) = x.data`
