### ISSUE TITLE
Remove Tracker dependency?

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/NamedDims.jl#53]
I understand that Tracker is added here so that this package works nicely with Flux + Tracker... and that that is useful... and _maybe_ we can stop supporting Tracker when it stops being the default AutoDiff for Flux...

BUT it's an ugly dependency I do not wish to add to a bunch of non-Flux-using packages where I would like to use NamedDims -- is there a way to avoid the Tracker dependency?

**Comment by oxinabox** [comment]
It doesn't really affect things though, maybe adds a second or so to the load time.
But I admit it grates on me too.

Lets use Requires.jl to do that.
It has the downside that it makes the world stop when loading the dependency,
but eventually that will be fixed,
and plus Tracker itself uses Requires anyway.

It does need care to make sure it only accepts acceptable versions of Tracker,
since this bypasses that package manager.

**Comment by nickrobinson251** [comment]
> It does need care to make sure it only accepts acceptable versions of Tracker

I do not think specifying package compatibility for a `@require`d package is possible?
